package pojo;
// Generated Oct 1, 2021 3:56:25 AM by Hibernate Tools 4.3.1

import DAO.DAOCustomer;
import java.sql.ResultSet;
import java.util.List;
import javax.faces.bean.ManagedBean;




/**
 * TblCust generated by hbm2java
 */
@ManagedBean
public class TblCust  implements java.io.Serializable {


     private Integer idCustomer;
     private String nameCust;
     private String email;
      private Integer noTlpn;
     private String book;

    public String getNameCust() {
        return nameCust;
    }

    public void setNameCust(String nameCust) {
        this.nameCust = nameCust;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Integer getNoTlpn() {
        return noTlpn;
    }

    public void setNoTlpn(Integer noTlpn) {
        this.noTlpn = noTlpn;
    }

    public String getBook() {
        return book;
    }

    public void setBook(String book) {
        this.book = book;
    }
    

    public String save_Customer()
    {
        DAOCustomer adddd = new DAOCustomer();
        adddd.add_product(this);
        return "index";
    }
    
    
    public List<TblCust> getAllRecoordss()
    {
        DAOCustomer cus = new DAOCustomer();
        List<TblCust> lCus = cus.retreveTblCust();
        return lCus;
    }
    
    
    public String getByIdcus()
    {
        String id_cust = idCustomer.toString();
        DAOCustomer cus = new DAOCustomer();
        List<TblCust> lCus = cus.getbyID(id_cust);
        nameCust = lCus.get(0).getNameCust();
        email = lCus.get(0).getEmail();
        noTlpn = lCus.get(0).getNoTlpn();
        book = lCus.get(0).getBook();
        return"dashboard";
    }
    
    
    public String editta(){
        DAOCustomer cus = new DAOCustomer();
        cus.editCustomer(this);
        nameCust = "";
        email = "";
        noTlpn = 0;
        book = "";
        return "dashboard";
    }
    
    
    public String deleteea(){
        DAOCustomer cus = new DAOCustomer();
        cus.deleteCustomer(idCustomer);
        nameCust = "";
        email = "";
        noTlpn = 0;
        book = "";
        return "dashboard"; 
    } 
    
    public String retsete(){
        DAOCustomer cus = new DAOCustomer();
        cus.resetCustomer(this);
        nameCust = "";
        email = "";
        noTlpn = 0;
        book = "";
        return "dashboard";
    }
     
     
    public TblCust() {
    }

    public TblCust(String nameCust, String email, Integer noTlpn, String book) {
       this.nameCust = nameCust;
       this.email = email;
       this.noTlpn = noTlpn;
       this.book = book;
    }
   
    public Integer getIdCustomer() {
        return this.idCustomer;
    }
    
    public void setIdCustomer(Integer idCustomer) {
        this.idCustomer = idCustomer;
    }
 
}


