package pojo;
// Generated Oct 1, 2021 3:56:25 AM by Hibernate Tools 4.3.1

import DAO.DAOLogin2;
import DAO.DAOuser2;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;




/**
 * TblUser generated by hbm2java
 */
@ManagedBean
public class TblUser2  implements java.io.Serializable {


     private Integer idUser;
     private String password;
     private String username;
     private String email;

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
     
     public void save_user()
     {
       DAOLogin2 add = new DAOLogin2();
       add.add_user(this);
     }
     
     public String login_user()
     {
         DAOLogin2 uDao = new DAOLogin2();
         List<TblUser2> us = uDao.getBy(username, password);
         try{
            if(us != null){
                username = us.get(0).username;
                password = us.get(0).password;
                
                return"rumah";
            }
         } catch (Exception e){
             System.out.println(e);
         }
         return "gagal";  
     }
     
     public String log_us()
     {
         DAOLogin2 uDao = new DAOLogin2();
         List<TblUser2> us = uDao.getBy(username, password);
         try{
            if(us != null){
                username = us.get(0).username;
                password = us.get(0).password;
                
                return"dashboard";
            }
         } catch (Exception e){
             System.out.println(e);
         }
         return "gagal";  
     }
     
     public List<TblUser2> getAllRecords()
     {
         DAOuser2 usr = new DAOuser2();
         List<TblUser2> lUsr = usr.retrveTblUser();
         return lUsr;
     }

     
     public String getByIdus()
     {
         String id_user = idUser.toString();
         DAOuser2 usr = new DAOuser2();
         List<TblUser2> lUsr = usr.getbyID(id_user);
         username = lUsr.get(0).username;
         password = lUsr.get(0).password;
         return"admin";
     }
     
     
     public String edit(){
         DAOuser2 usr = new DAOuser2();
         usr.editUser(this);
         username ="";
         password ="";
         return"admin";
     }  
     
     
     public String delete(){
//         String id_user = idUser.toString();
         DAOuser2 usr = new DAOuser2();
         usr.deleteUser(idUser);
         username ="";
         password ="";
         
         return"admin";
     }
     
     public String retse(){
        DAOuser2 usr = new DAOuser2();
        usr.resetUser(this);
        username ="";
         password ="";
         
         return"admin";
    }
     
    public TblUser2() {
    }

    public TblUser2(String password, String username) {
       this.password = password;
       this.username = username;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }




}
